---
title: "Efficiency filtering for subtypes"
author: "Xenia Quaas"
date: "28 5 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
load("../2021-topic-01-team-03/dataset/prism_datasets.rda")
load("../2021-topic-01-team-03/dataset/cellline_datasets.rda")
```

# Cedrik´s clustering
# Clustering of the effective drugs 

## d7 sets 


```{r}

## calculate the means for each drug in a subtype 
astrocytoma_ae_d7_mean = colMeans(astrocytoma_ae_d7)
glioma_ae_d7_mean = colMeans(glioma_ae_d7)
glioblastoma_ae_d7_mean = colMeans(glioblastoma_ae_d7)
medulloblastoma_ae_d7_mean = colMeans(medulloblastoma_ae_d7)

## create a combined data frame with all the means from each subtype 
means_eff <- data.frame(Astrocytoma = astrocytoma_ae_d7_mean,
                        Glioma = glioma_ae_d7_mean, 
                        Glioblastoma = glioblastoma_ae_d7_mean,  
                        Medulloblastoma = medulloblastoma_ae_d7_mean)
rownames(means_eff) = effective_in_all_doses

means_drugs <- data.frame(means_eff, 
                          Means = apply(means_eff, 1 , mean))

new_means_eff <- data.frame(Efficiency = c(means_drugs$Astrocytoma, means_drugs$Glioma, means_drugs$Glioblastoma, means_drugs$Medulloblastoma), 
                            Drug_Mean = c(means_drugs$Means, means_drugs$Means, means_drugs$Means, means_drugs$Means), 
                            subtype = c(rep("Astrocytoma", nrow(means_drugs)),
                                      rep("Glioma", nrow(means_drugs)),
                                      rep("Glioblastoma", nrow(means_drugs)),
                                      rep("Medulloblastoma", nrow(means_drugs))), 
                            Drug = c(effective_in_all_doses, effective_in_all_doses, effective_in_all_doses, effective_in_all_doses))

## create a new boxplot that shows the overall the distribution and 

p <- ggplot(new_means_eff, aes(x = subtype, y = Efficiency, color = subtype)) + 
                         ggtitle("Subtype Boxplots") +
                          xlab("Subtypes") + 
                          ylab("Efficiency") + 
  geom_boxplot(outlier.colour="red", outlier.shape=8,
                outlier.size=4)
p + theme(legend.position = "none")
```

## Plotting all of the individual subtyp means 

```{r}

## rearrange the Values in descending order 

first = new_means_eff$Drug_Mean
second = sort(new_means_eff$Drug_Mean, decreasing = TRUE)
              


arrangement <- data.frame(Drug_Ranks = match(first, second), 
                                Efficiency = new_means_eff$Efficiency, 
                                Subtype = new_means_eff$subtype,
                                Drug = new_means_eff$Drug, 
                                Drug_Mean = new_means_eff$Drug_Mean)
res <- 1 

for(i in c(1:51)){zv <- rep(i,4);res <- c(res, zv)}

vec <- res[2:205]
pre_arrangement <- arrange(arrangement, Drug_Ranks)
pre_arrangement <- data.frame(pre_arrangement, 
                               Numbers = vec)

```


```{r}
## Plot the new, rearranged subtypes 
ggplot(pre_arrangement, aes(x = Numbers , y = Efficiency, color = Subtype)) + 
                         ggtitle("Means of subtypes") +
                          xlab("Drugs") + 
                          ylab("Efficiency") + 
  
  geom_point(aes(shape=Subtype))


##auffallend sind die Medulloblastoma, die in 31 von 51 Fällen effektiver sind als alle anderen Drogen!!!  Drogen 24, 26, 32 und 33 


```















