---
title: "Clustering exp"
author: "Cedrik Neber"
date: "7/9/2021"
output: html_document
---

## Clustering of the exp value 

You can also embed plots, for example:

```{r pressure, echo=FALSE}
exp <- brain_cancer_exp[,top_genes]

medulloblastoma_c <- apply(exp[medulloblastoma,],2, mean)
#medulloblastoma_c$celline <- medulloblastoma
glioblastoma_c <- apply(exp[glioblastoma,],2, mean)
#glioblastoma_c$celline <- glioblastoma
glioma_c <- apply(exp[glioma,],2, mean)
#glioma_c$celline <- glioma
astrocytoma_c <- apply(exp[astrocytoma,],2, mean)
#astrocytoma_c$celline <- astrocytoma

clustering.frame <- data.frame(Expression = c(medulloblastoma_c, glioblastoma_c, glioma_c, astrocytoma_c), 
                              Subtype = c(rep("Medulloblastoma",20), rep("Glioblastoma", 20), rep("Glioma", 20), rep("Astrocytoma", 20)))


```
## PCA before applying the kmeans 

```{r}
#scale data before PCA 
#exp_s <- scale(exp)
#PCA 
exp_pca <- prcomp(exp)
summary(exp_pca) 
library(factoextra)
fviz_eig(exp_pca)

```


## kmeans for the clustering.frame 

```{r}
PC <- as.data.frame(exp_pca$x)
PC1 <- PC$PC1
PC2 <- PC$PC2

## Porper kmeans after PCA 

km_c <- kmeans(exp_pca$x, 4, iter.max = 100, nstart = 1)
km_c

gg_pca <- data.frame( PC1 = PC1,
                      PC2 = PC2, 
                      Cell_line = rownames(exp), 
                      Subtype = brain_cancer_cl$disease_subtype, 
                      Cluster = km_c$cluster)

ggplot(gg_pca, aes( x = PC1, y = PC2, color = Cluster, shape = Subtype)) +
  ggtitle("Cell line clustering") +
  xlab("PC1") + 
  ylab("PC2")+ 
  geom_point()

 

```

```{r}
cls <- kmeans(x = exp_pca$x, centers = 4)
km_c$cluster <- as.character(cls$cluster)
head(cls)

ggplot() +
  geom_point(data = km_c, 
             mapping = aes(x = PC1, 
                                  y = PC2, 
                                  colour = cluster))
```

```{r}
library(cluster)

dis = dist(t(exp))
head(dis)
#s = silhouette(km_c$cluster, dis)
plot(s)


#ggheatmap(exp, orderCol = T, orderRow = T, dendroLineSize = 0.5,
  #fontSize = 20, colorScheme = "Spectral", scaleName = "value",
  #distMethod = "euclidean", clustMethod = "complete")

#ggplot(as.matrix(exp)
#geom_tile()

km_c$cluster 
medulloblastoma 
#3,2  
glioblastoma 
#4, 4, 1, 1, 1, 1, 4
glioma 
#3, 1, 2, 4, 2
astrocytoma
#2, 2, 2, 2, 2, 3, 4, 
```

```{r}
install.packages(FactoMineR)
library(FactoMineR)
res.pca <- PCA(exp, ncp = 10, graph = FALSE)
res.hcpc <- HCPC(res.pca, graph = FALSE)

dendo <- fviz_dend(res.hcpc, 
          cex = 0.7,                    
          palette = "jco",               
          rect = TRUE, rect_fill = TRUE, 
          rect_border = "jco",           
          labels_track_height = 0.8      
          )
dendo



cluster <- fviz_cluster(res.hcpc,
             repel = TRUE,            
             show.clust.cent = TRUE, 
             palette = "jco",         
             ggtheme = theme_minimal(),
             main = "Cell line clustering", 
             ggtjem = theme_minimal()
             )
cluster
```






