---
title: "Topic 1 Group 3: Drug viability screens for oncological and non-oncological treatments"
author: "Cedrik Neber, Lea Ahrens, Lennard Kleemann, Ilya Schneider, Xenia Quaas"
date: "19 7 2021"
output:
  html_document: default
---

Drug repurposing is a strategy in which already authorized drugs are used to treat diseases for which they were not intended. This has advantages, especially in terms of cost, time and the risk to fail in research and development of a new drug. In this context, computational approaches are gaining in importance, as they allow large amounts of data to be analyzed (Pushpakom *et al.*, 2019).

According to the Global Cancer Statistics 2020, brain cancer is a rarer cancer type, accounting for 2,5% of all new cancers. Nevertheless, its mortality rate is comparatively high, which makes drug repurposing an interesting application.


#Structure of our project

This project uses seven datasets generated by the Broad Institute using the PRISM strategy. It investigates the general question of whether it is possible to predict the effectiveness of a drug in the treatment of brain cancer. 

To explore our main question, we examined four milestones:

**1) How can we distinguish the most effective drugs?**
**2) What are the targets of the effective drugs?**
**3) Are there any genetic markers that are specific for brain cancer subtypes?**
**4) What other factors contribute to drug and effectiveness prediction?**


#Data Clean up

As the datasets also contain information on other cancer types, we removed non-relevant cell lines. In addition, we classified the datasets according to brain cancer subtypes, as this information was used for later analyses. We treated NA values either by removing the cell line or by replacing it with a mean value, depending on the dataset. 


#Identification of effective drugs

The `prism` data frame gives information on treatments which were used in the screening effort. These treatments include 4,518 drugs with doses ranging from 0.00061034 $\mu M to 10 $\mu M. There are 8 standard doses into which we have divided the data frame by creating a list. 

Nevertheless, treatments were given whose doses did not correspond to the standard one's. We have assigned these to the standard doses to which there is the least deviation, assuming that the focus of the project is on the drug itself and not on the dose used. 

To identify the most effective drugs, we looked at the effectiveness values of the `prism` data frame. The more negative the value, the more effective the treatment. Contrary to the threshold value 0.3 of Corsello *et al.* we have set the threshold value 0.2.

In order to reduce the number of drugs and to be able to make later predictions independent of the dose, we finally selected drugs that are effective in all doses. 



2) What are the targets of the effective drugs?
3) Are there any genetic markers that are specific for brain cancer subtypes?
- Examine gene targets of the effective drugs
- Find a relationship between gene targets and brain cancer subtypes
- Wilcoxon Signed Rank Test


4) What other factors contribute to predicting the effectiveness of a drug? 
- Estimate the relevant variables
- Look for correlations between variables and leave only variables with high variance
- Reduce the amount of dimensions by conducting a PCA
- Regression model with PCA
- Compare the real effectiveness with the estimated one 


Rough version with possible visualizations:

Q1:
- Visualization of effectiveness for every doses via eight *histograms* with median
- Visualization of effective drugs after filtering for drugs effective in every cell type via Cedrik's *clustering* 
- Showing differences in the effectiveness between subtypes by *boxplots*?

Q3:
- Visualization of most relevant genes in cell lines via a *heatmap* with shows the degree of expression